/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackArrow: typeof import('./src/components/BackArrow.vue')['default']
    Calculator: typeof import('./src/components/Calculator/index.vue')['default']
    Counter: typeof import('./src/components/Counter/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCalculator: typeof import('./src/components/icons/IconCalculator.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCountdown: typeof import('./src/components/icons/IconCountdown.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTodo: typeof import('./src/components/icons/IconTodo.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconWeather: typeof import('./src/components/icons/IconWeather.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToDo: typeof import('./src/components/ToDo/ToDo.vue')['default']
    TodoForm: typeof import('./src/components/ToDo/TodoForm.vue')['default']
    TrashCan: typeof import('./src/components/icons/TrashCan.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
